name: Build Shinylive Links

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install shinylive
        run: |
          pip install shinylive
          # Verify installation
          shinylive --version

      - name: Build all example apps
        run: |
          ./scripts/build-all-examples.sh

      - name: Generate shinylive redirect pages
        run: |
          python scripts/generate-shinylive-links.py

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: shinylive-pages

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
